const token=()=>localStorage.getItem('accessToken');
export const hasSession=()=>Boolean(token());
export const logout=()=>{localStorage.removeItem('accessToken');window.dispatchEvent(new Event('auth-changed'));};
export class ApiError extends Error{constructor(message,status){super(message);this.status=status;}}
async function request(path,options={}){const{timeout=15000,...fetchOptions}=options,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout),authenticated=!path.startsWith('/api/v1/auth/')&&token(),isAuthProbe=path==='/api/v1/users/me'||path==='/api/v1/notifications';try{const response=await fetch(path,{...fetchOptions,credentials:'same-origin',signal:controller.signal,headers:{...fetchOptions.headers,...(authenticated?{Authorization:`Bearer ${token()}`}:{})}});if(!response.ok){const body=await response.json().catch(()=>null);if(response.status===401||(authenticated&&response.status===403&&isAuthProbe)){logout();throw new ApiError('Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',401);}throw new ApiError(body?.detail||body?.message||'Không thể xử lý yêu cầu.',response.status);}const text=await response.text();return text?JSON.parse(text):null;}catch(error){if(error.name==='AbortError')throw new ApiError('Kết nối quá lâu. Vui lòng thử lại.',408);throw error;}finally{clearTimeout(timer);}}
export const newestListings=()=>request('/api/v1/listings');
export const categories=()=>request('/api/v1/categories');
export const locations=()=>request('/api/v1/locations');
export const myListings=()=>request('/api/v1/listings/mine');
export const me=()=>request('/api/v1/users/me');
export const user=id=>request(`/api/v1/users/${id}`);
export const updateUser=(id,displayName)=>request(`/api/v1/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName})});
export const changePassword=(currentPassword,newPassword)=>request('/api/v1/auth/password-changes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});
export const searchListings=params=>request(`/api/v1/listings?${new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null))}`);
export const listing=id=>request(`/api/v1/listings/${id}`);
export const images=id=>request(`/api/v1/listings/${id}/images`);
export const comments=id=>request(`/api/v1/listings/${id}/comments`);
export const addComment=(id,body)=>request(`/api/v1/listings/${id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body})});
export const uploadImage=(id,file)=>{const body=new FormData();body.append('file',file);return request(`/api/v1/listings/${id}/images`,{method:'POST',body});};
export const deleteImage=(listingId,mediaId)=>request(`/api/v1/listings/${listingId}/images/${mediaId}`,{method:'DELETE'});
export const reportListing=(id,reasonId,details)=>request(`/api/v1/listings/${id}/reports`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reasonId,details})});
export const openConversation=id=>request(`/api/v1/listings/${id}/conversations`,{method:'POST'});
export const conversations=()=>request('/api/v1/conversations');
export const conversationMessages=id=>request(`/api/v1/conversations/${id}/messages`);
export const sendMessage=(id,body)=>request(`/api/v1/conversations/${id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body})});
export const followSeller=id=>request(`/api/v1/sellers/${id}/follow`,{method:'POST'});
export const sellerTrust=id=>request(`/api/v1/sellers/${id}/trust-score`);
export const savedListingIds=()=>request('/api/v1/saved-listings/ids');
export const saveListing=id=>request(`/api/v1/listings/${id}/saved`,{method:'POST'});
export const unsaveListing=id=>request(`/api/v1/listings/${id}/saved`,{method:'DELETE'});
export const requestPasswordReset=email=>request('/api/v1/auth/password-reset-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});
export const notifications=()=>request('/api/v1/notifications');
export const readNotification=id=>request(`/api/v1/notifications/${id}/read`,{method:'PATCH'});
export const myTransactions=()=>request('/api/v1/transactions/mine');
export const confirmTransaction=(listingId,buyerUserId)=>request(`/api/v1/listings/${listingId}/transactions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buyerUserId})});
export const confirmReceipt=id=>request(`/api/v1/transactions/${id}/confirm`,{method:'POST'});
export const createReview=(id,rating,body)=>request(`/api/v1/transactions/${id}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating:Number(rating),body})});
export const adminReports=()=>request('/api/v1/admin/reports');
export const adminArchive=id=>request(`/api/v1/admin/listings/${id}/archive`,{method:'PATCH'});
export const adminDismissReport=id=>request(`/api/v1/admin/reports/${id}/dismiss`,{method:'PATCH'});
export const adminArchiveReport=id=>request(`/api/v1/admin/reports/${id}/archive`,{method:'PATCH'});
export const login=(email,password)=>request('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}).then(data=>(localStorage.setItem('accessToken',data.accessToken),window.dispatchEvent(new Event('auth-changed')),data));
export const createListing=data=>request('/api/v1/listings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
export const updateListing=(id,data)=>request(`/api/v1/listings/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
export const archiveListing=id=>request(`/api/v1/listings/${id}`,{method:'DELETE'});
export const register=(displayName,email,password)=>request('/api/v1/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName,email,password})}).then(data=>(localStorage.setItem('accessToken',data.accessToken),window.dispatchEvent(new Event('auth-changed')),data));
